import os
import re
import secrets
import threading
from functools import lru_cache

NO_ID_TABLES = {"email_otp", "password_otp", "user_projects", "locations"}

import bcrypt

from . import config  # noqa: F401  (imported for the .env side effect)

_SEED_PW_CHARS = "ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789"


def _looks_like_postgres(url: str) -> bool:
    return url.startswith((
        "postgresql://", "postgresql+psycopg://", "postgresql+psycopg2://", "postgres://",
    ))


def _normalize_pg_url(url: str) -> str:
    for prefix in ("postgresql+psycopg://", "postgresql+psycopg2://", "postgres://"):
        if url.startswith(prefix):
            return "postgresql://" + url[len(prefix):]
    return url


DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL is not set. This app runs on Postgres (Supabase) only —"
        " put the connection URL in server-python/.env."
    )
if not _looks_like_postgres(DATABASE_URL):
    raise RuntimeError(
        f"DATABASE_URL does not look like Postgres: {DATABASE_URL[:24]}… —"
        " expected postgresql://, postgres:// or postgresql+psycopg://."
    )
_PG_URL = _normalize_pg_url(DATABASE_URL)

import psycopg

INTEGRITY_ERRORS = (psycopg.IntegrityError,)


_PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 TEXT NOT NULL,
  email                TEXT NOT NULL UNIQUE,
  role                 TEXT NOT NULL CHECK (role IN ('Super Admin','Admin','Team','Client')),
  password_hash        TEXT NOT NULL,
  must_change_password INTEGER NOT NULL DEFAULT 0,
  status               TEXT NOT NULL DEFAULT 'invited' CHECK (status IN ('invited','active')),
  totp_secret          TEXT,
  totp_enabled         INTEGER NOT NULL DEFAULT 0,
  created_at           TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS emails (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  to_email TEXT NOT NULL,
  cc_email TEXT,
  subject  TEXT NOT NULL,
  body     TEXT NOT NULL,
  sent_at  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
-- Both to_email and cc_email hold a comma-separated list: a report goes to its
-- recipients in one message, so "who received this" is a set, not one address.
ALTER TABLE emails ADD COLUMN IF NOT EXISTS cc_email TEXT;
-- The rest of the email columns, plus email_events, are further down: they
-- reference projects and users, which this script has not created yet.

CREATE TABLE IF NOT EXISTS locations (
  location_code INTEGER PRIMARY KEY,
  name          TEXT NOT NULL,
  full_name     TEXT NOT NULL,
  kind          TEXT NOT NULL CHECK (kind IN ('country','region','city')),
  country_code  INTEGER,
  region_code   INTEGER,
  country_iso   TEXT,
  location_type TEXT,
  alt           TEXT NOT NULL DEFAULT '',
  name_key      TEXT,
  search_key    TEXT
);
ALTER TABLE locations ADD COLUMN IF NOT EXISTS name_key   TEXT;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS search_key TEXT;

DROP INDEX IF EXISTS idx_locations_kind_name;
DROP INDEX IF EXISTS idx_locations_kind_country;
DROP INDEX IF EXISTS idx_locations_kind_region;

CREATE INDEX IF NOT EXISTS idx_locations_key
  ON locations (kind, name_key text_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_locations_country_key
  ON locations (kind, country_code, name_key text_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_locations_region_key
  ON locations (kind, region_code, name_key text_pattern_ops);

-- NOTE: the trigram index for the autocomplete's substring pass lives in
-- _OPTIONAL_DDL below, because CREATE EXTENSION needs privileges that a managed
-- database may not grant and must not be able to abort the whole schema.

CREATE TABLE IF NOT EXISTS projects (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL,
  client_name     TEXT,
  domain          TEXT,
  location_code   INTEGER,
  country_code    INTEGER,
  region_code     INTEGER,
  city_code       INTEGER,
  location_label  TEXT,
  ga_property_id  TEXT,
  gsc_site_url    TEXT,
  active          INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS country_code   INTEGER;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS region_code    INTEGER;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS city_code      INTEGER;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS location_label TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_name    TEXT;

CREATE TABLE IF NOT EXISTS keywords (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id    INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  term          TEXT NOT NULL,
  current_rank  INTEGER CHECK (current_rank >= 1),
  previous_rank INTEGER CHECK (previous_rank >= 1),
  last_checked  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD'),
  created_at    TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS snapshots (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  period_key  TEXT NOT NULL,
  label       TEXT NOT NULL,
  captured_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD'),
  created_at  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  source      TEXT NOT NULL DEFAULT 'manual',
  locked      INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS snapshot_ranks (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id  INTEGER NOT NULL REFERENCES snapshots(id) ON DELETE CASCADE,
  keyword_id   INTEGER REFERENCES keywords(id) ON DELETE SET NULL,
  term         TEXT NOT NULL,
  rank         INTEGER,
  last_checked TEXT
);

CREATE TABLE IF NOT EXISTS moz_metrics (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id       INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  domain           TEXT NOT NULL,
  domain_authority INTEGER,
  linking_domains  INTEGER,
  inbound_links    INTEGER,
  ranking_keywords INTEGER,
  spam_score       REAL,
  raw_json         TEXT,
  fetched_at       TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_projects (
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, project_id)
);

CREATE TABLE IF NOT EXISTS report_version (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id        INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  period_key        TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','in_review','sent')),
  parent_version_id INTEGER REFERENCES report_version(id) ON DELETE SET NULL,
  data_json         TEXT NOT NULL,
  content_json      TEXT NOT NULL DEFAULT '{}',
  rank_snapshot_id  INTEGER REFERENCES snapshots(id) ON DELETE SET NULL,
  created_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at        TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  frozen_at         TEXT
);

CREATE INDEX IF NOT EXISTS idx_report_version_project_period
  ON report_version (project_id, period_key);

CREATE TABLE IF NOT EXISTS backlinks (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  url         TEXT NOT NULL,
  month       TEXT NOT NULL,
  created_at  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(project_id, month, url)
);

CREATE INDEX IF NOT EXISTS idx_backlinks_project_month
  ON backlinks (project_id, month);

CREATE INDEX IF NOT EXISTS idx_keywords_project_created
  ON keywords (project_id, created_at, id);

CREATE TABLE IF NOT EXISTS keyword_ranks (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword_id INTEGER NOT NULL REFERENCES keywords(id) ON DELETE CASCADE,
  month      TEXT NOT NULL,
  rank       INTEGER CHECK (rank IS NULL OR rank >= 1),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(keyword_id, month)
);

CREATE INDEX IF NOT EXISTS idx_keyword_ranks_month
  ON keyword_ranks (month, keyword_id);

CREATE TABLE IF NOT EXISTS posts (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  kind        TEXT NOT NULL CHECK (kind IN ('blog','linkedin')),
  url         TEXT NOT NULL,
  title       TEXT,
  month       TEXT,
  created_at  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_posts_project_kind ON posts (project_id, kind);
ALTER TABLE posts ADD COLUMN IF NOT EXISTS month TEXT;

CREATE INDEX IF NOT EXISTS idx_snapshot_ranks_snapshot
  ON snapshot_ranks (snapshot_id);
CREATE INDEX IF NOT EXISTS idx_snapshots_project_period
  ON snapshots (project_id, period_key);
CREATE INDEX IF NOT EXISTS idx_moz_metrics_project_fetched
  ON moz_metrics (project_id, fetched_at);

ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_secret TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_enabled INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS twofa_backup_codes (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash  TEXT NOT NULL,
  used_at    TEXT
);
CREATE INDEX IF NOT EXISTS idx_twofa_backup_user ON twofa_backup_codes (user_id);

CREATE TABLE IF NOT EXISTS email_otp (
  user_id     INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  code_hash   TEXT NOT NULL,
  expires_at  TEXT NOT NULL,
  attempts    INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS password_otp (
  user_id     INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  code_hash   TEXT NOT NULL,
  expires_at  TEXT NOT NULL,
  attempts    INTEGER NOT NULL DEFAULT 0
);

-- rank_check_log was created for an automatic SERP rank-check feature that was
-- never built. Nothing ever wrote a row. Dropped rather than left as a trap for
-- the next person reading the schema for a picture of how ranks are recorded —
-- every rank in this app is typed in by hand (see keyword_rank_service.py).
DROP TABLE IF EXISTS rank_check_log;

-- ── Foreign keys that had no index ───────────────────────────────────
-- Postgres does not index a referencing column automatically, so every parent
-- DELETE had to sequentially scan the child table to enforce the constraint.

-- snapshot_ranks.keyword_id is ON DELETE SET NULL: deleting one keyword scanned
-- every snapshot rank row ever recorded.
CREATE INDEX IF NOT EXISTS idx_snapshot_ranks_keyword
  ON snapshot_ranks (keyword_id);

-- The UNIQUE (user_id, project_id) index only serves lookups that lead with
-- user_id. Deleting a project, and the per-project GET /api/users query, both
-- filter or sort by project_id alone.
CREATE INDEX IF NOT EXISTS idx_user_projects_project
  ON user_projects (project_id);

-- report_version rows carry the large data_json/content_json payloads, so an
-- unindexed scan here is especially expensive.
CREATE INDEX IF NOT EXISTS idx_report_version_parent
  ON report_version (parent_version_id);
CREATE INDEX IF NOT EXISTS idx_report_version_snapshot
  ON report_version (rank_snapshot_id);
CREATE INDEX IF NOT EXISTS idx_report_version_created_by
  ON report_version (created_by);

-- list_versions orders by created_at DESC, id DESC; the existing
-- (project_id, period_key) index forced a separate sort.
CREATE INDEX IF NOT EXISTS idx_report_version_project_created
  ON report_version (project_id, created_at DESC, id DESC);

-- The report and posts queries filter on COALESCE(month, substr(created_at,1,7)),
-- which no plain column index can serve.
CREATE INDEX IF NOT EXISTS idx_posts_project_month_expr
  ON posts (project_id, (COALESCE(month, substr(created_at, 1, 7))));

-- Saved email recipients, one row per project, feeding the Send Report dialog
-- so addresses stop being typed by hand each time.
--
-- cc_emails is a JSONB array of addresses rather than fixed cc1/cc2/cc3 columns:
-- the dialog lets the user add and remove copies freely, and a fixed column
-- count would cap that at whatever number we guessed today.
--
-- The project's name is deliberately NOT duplicated here — it lives in
-- projects.name and is read through a join, so it can't go stale on a rename.
CREATE TABLE IF NOT EXISTS project_recipients (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id    INTEGER NOT NULL UNIQUE REFERENCES projects(id) ON DELETE CASCADE,
  primary_email TEXT NOT NULL,
  cc_emails     JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at    TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at    TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_project_recipients_project
  ON project_recipients (project_id);

-- ── Email delivery tracking ──────────────────────────────────────────
-- `emails` was a write-only outbox log: it recorded that we handed a message to
-- the provider and nothing after that. The columns below turn each row into the
-- current state of one message, kept up to date by Brevo's event webhook
-- (routers/webhooks.py). The per-event history lives in email_events; what is
-- denormalised onto `emails` is only what the Email Log screen sorts and
-- filters on, so listing 50 messages never has to aggregate a second table.
--
-- This block sits at the end of the script rather than beside the emails table
-- because project_id and sent_by reference tables created further up.
--
-- message_id is Brevo's own id (e.g. <2026...@smtp-relay.mailin.fr>), returned
-- by the send call and echoed back on every webhook event. It is the join key.
-- Deliberately not UNIQUE: a send that failed outright has no id, and a unique
-- constraint would then let only one failure exist.
ALTER TABLE emails ADD COLUMN IF NOT EXISTS message_id TEXT;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS provider   TEXT;
-- 'report' | 'invite' | 'password_code' | 'login_code' | 'other' — set by the
-- send helper, so the log can be filtered without pattern-matching subjects.
ALTER TABLE emails ADD COLUMN IF NOT EXISTS category   TEXT NOT NULL DEFAULT 'other';
ALTER TABLE emails ADD COLUMN IF NOT EXISTS status     TEXT NOT NULL DEFAULT 'queued';
ALTER TABLE emails ADD COLUMN IF NOT EXISTS error      TEXT;
-- The HTML actually sent, so the detail drawer shows the message the client
-- saw rather than the text fallback. Report emails are ~10 KB of table markup.
ALTER TABLE emails ADD COLUMN IF NOT EXISTS html_body  TEXT;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS attachment_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS sent_by    INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS delivered_at    TEXT;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS first_opened_at TEXT;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS last_opened_at  TEXT;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS last_event_at   TEXT;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS open_count  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS click_count INTEGER NOT NULL DEFAULT 0;
-- When the first link was clicked. click_count alone answered "did they" but not
-- "when", which is the more useful half: a click hours after delivery says
-- something different from one in the same minute. Only the first is recorded —
-- a last_clicked_at would be a column nothing reads.
ALTER TABLE emails ADD COLUMN IF NOT EXISTS first_clicked_at TEXT;

-- One-time backfill for rows that predate the columns above. ADD COLUMN fills
-- every existing row with the default, so without this the whole history reads
-- "Queued" on the Email Log and the "still in flight" figure counts messages
-- that were handed to the provider months ago.
--
-- 'sent' rather than 'delivered': all we ever knew about these is that the send
-- call succeeded. Claiming delivery we never observed would be worse than the
-- vaguer truth.
--
-- The date is hardcoded and in the past on purpose. It scopes this to rows
-- written before the feature shipped, so a genuinely queued row created by a
-- concurrent send can't be flipped to 'sent' by a second worker booting. Safe
-- to re-run: after the first pass nothing matches.
UPDATE emails
   SET status = 'sent'
 WHERE status = 'queued'
   AND message_id IS NULL
   AND sent_at < '2026-08-12';

-- One row per provider event. Append-only: the columns above are a rollup of
-- this table, and this is what the detail drawer's timeline reads.
--
-- email_id is nullable because a webhook can arrive for a message we can no
-- longer match — a send from before this feature existed, or one whose emails
-- row was deleted. Those are still stored: an unmatched bounce is exactly the
-- kind of thing someone goes looking for later.
--
-- message_id and recipient are NOT NULL DEFAULT '' rather than nullable so the
-- dedupe index below actually works; in Postgres two NULLs are distinct, so a
-- nullable column in a UNIQUE index silently lets duplicates through.
CREATE TABLE IF NOT EXISTS email_events (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_id    INTEGER REFERENCES emails(id) ON DELETE CASCADE,
  message_id  TEXT NOT NULL DEFAULT '',
  recipient   TEXT NOT NULL DEFAULT '',
  event       TEXT NOT NULL,
  occurred_at TEXT NOT NULL,
  reason      TEXT,
  link        TEXT,
  user_agent  TEXT,
  ip          TEXT,
  raw         JSONB,
  received_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

-- Brevo retries any webhook it did not get a 2xx from, and occasionally sends
-- the same event twice unprompted. Ingestion is INSERT OR IGNORE against this
-- index, so a replayed batch is a no-op instead of inflating the open count.
CREATE UNIQUE INDEX IF NOT EXISTS idx_email_events_dedupe
  ON email_events (message_id, event, recipient, occurred_at);

CREATE INDEX IF NOT EXISTS idx_email_events_email
  ON email_events (email_id, occurred_at DESC, id DESC);

-- The webhook's hot path: match an incoming event to its emails row.
CREATE INDEX IF NOT EXISTS idx_emails_message_id
  ON emails (message_id);

-- The Email Log list is ordered by sent_at DESC, id DESC.
CREATE INDEX IF NOT EXISTS idx_emails_sent_at
  ON emails (sent_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_emails_project
  ON emails (project_id);
"""


#: Applied one statement at a time, each tolerant of failure.
#:
#: The location autocomplete's second pass matches `search_key LIKE '%token%'`.
#: A leading wildcard can't use a btree index, so that pass sequentially scanned
#: the whole locations table — around 100k rows after a full DataForSEO import —
#: on every keystroke. A trigram GIN index makes substring matching indexable.
#:
#: pg_trgm ships with Postgres and is available on Supabase, but creating an
#: extension needs privileges a managed database may withhold. If either
#: statement fails the app keeps working exactly as before, just without the
#: index, so these are kept out of the main schema script.
#:
#: The unique index on keywords is here for a different reason: a database that
#: already contains duplicate terms will reject it, and that must not stop the
#: app from booting. Run `python -m scripts.dedupe_keywords --commit` to merge
#: the duplicates, after which this statement succeeds on the next start. Until
#: then add_keyword's own pre-insert check is the only guard, which is racy but
#: no worse than the behaviour it replaces.
_OPTIONAL_DDL = (
    "CREATE EXTENSION IF NOT EXISTS pg_trgm",
    "CREATE INDEX IF NOT EXISTS idx_locations_search_trgm"
    " ON locations USING gin (search_key gin_trgm_ops)",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_keywords_project_term"
    " ON keywords (project_id, term)",
)


@lru_cache(maxsize=2048)
def _translate(sql: str, returning: bool = True) -> str:
    """SQLite-flavoured SQL -> Postgres.

    Cached: the SQL strings in this codebase are literals, so the same handful of
    statements are translated over and over. Without the cache this ran several
    str.replace passes plus a regex on every single query.
    """
    s = sql
    s = s.replace("strftime('%Y-%m','now')", "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM')")
    s = s.replace("datetime('now')", "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')")
    s = s.replace("date('now')", "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD')")

    head = s.lstrip()[:24].upper()
    if head.startswith("INSERT OR IGNORE"):
        i = s.upper().index("INSERT OR IGNORE")
        s = s[:i] + "INSERT" + s[i + len("INSERT OR IGNORE"):]
        if "ON CONFLICT" not in s.upper():
            s = s.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    elif returning and head.startswith("INSERT") and "RETURNING" not in s.upper():
        m = re.search(r"insert\s+into\s+\"?([a-zA-Z_]\w*)\"?", s, re.IGNORECASE)
        table = m.group(1).lower() if m else ""
        if table not in NO_ID_TABLES:
            s = s.rstrip().rstrip(";") + " RETURNING id"

    s = s.replace("?", "%s")
    return s


class _Row:

    __slots__ = ("_names", "_vals", "_index")

    def __init__(self, names, values):
        self._names = names
        self._vals = values
        self._index = None

    def __getitem__(self, key):
        if isinstance(key, str):
            if self._index is None:
                self._index = {n: i for i, n in enumerate(self._names)}
            return self._vals[self._index[key]]
        return self._vals[key]

    def __iter__(self):
        return iter(self._vals)

    def __len__(self):
        return len(self._vals)

    def keys(self):
        return list(self._names)

    def get(self, key, default=None):
        try:
            return self[key]
        except (KeyError, IndexError):
            return default


def _pg_row_factory(cursor):
    cols = cursor.description
    names = [c.name for c in cols] if cols else []

    def make_row(values):
        return _Row(names, values)

    return make_row


class _PgCursor:
    """Materialises the result and closes the underlying cursor immediately.

    The previous version held an open psycopg cursor for the caller to fetch from
    later. That was survivable when every connection was thrown away after one
    request, but with a pool the connections are long-lived and those cursors
    piled up on them until garbage collection. psycopg buffers the whole result
    for a client-side cursor anyway, so reading it out here costs no extra memory.
    """

    __slots__ = ("lastrowid", "rowcount", "_rows", "_pos")

    def __init__(self, cur, translated_sql):
        self.lastrowid = None
        self.rowcount = cur.rowcount
        self._rows = []
        self._pos = 0
        try:
            if translated_sql.lstrip()[:6].upper() == "INSERT" and "RETURNING" in translated_sql.upper():
                # Consume the RETURNING row into lastrowid and expose nothing,
                # matching the previous behaviour exactly.
                row = cur.fetchone()
                self.lastrowid = row[0] if row is not None else None
            elif cur.description is not None:
                self._rows = cur.fetchall()
        finally:
            cur.close()

    def fetchone(self):
        if self._pos >= len(self._rows):
            return None
        row = self._rows[self._pos]
        self._pos += 1
        return row

    def fetchall(self):
        rows = self._rows[self._pos:]
        self._pos = len(self._rows)
        return rows

    def fetchmany(self, size=None):
        if size is None:
            size = len(self._rows) - self._pos
        rows = self._rows[self._pos:self._pos + size]
        self._pos += len(rows)
        return rows


class _PgConnection:

    __slots__ = ("_conn", "_owned")

    def __init__(self, conn, owned: bool = True):
        self._conn = conn
        # Pooled connections are borrowed: close() must hand them back, not tear
        # down the socket.
        self._owned = owned

    def execute(self, sql, params=()):
        translated = _translate(sql)
        cur = self._conn.cursor()
        cur.execute(translated, params or None)
        return _PgCursor(cur, translated)

    def executemany(self, sql, seq_of_params):
        translated = _translate(sql, returning=False)
        rows = list(seq_of_params)
        cur = self._conn.cursor()
        if rows:
            cur.executemany(translated, rows)
        return _PgCursor(cur, translated)

    def transaction(self):
        """Group several statements so they commit or roll back together.

        Connections are opened with autocommit=True, which means every execute()
        is its own transaction. That is the right default for this app's
        single-statement handlers, but it silently makes multi-row writes
        non-atomic: a loop that raises halfway leaves the earlier rows
        committed. Any handler writing more than one row should wrap the writes:

            with db.transaction():
                db.executemany(...)
                db.executemany(...)

        psycopg emits BEGIN on entry and COMMIT (or ROLLBACK, on exception) on
        exit, and nests correctly via savepoints if one of these is already open.
        """
        return self._conn.transaction()

    def close(self):
        if self._owned:
            self._conn.close()


_pool = None
_pool_lock = threading.Lock()
_pool_unavailable = False

POOL_MIN = int(os.environ.get("DB_POOL_MIN", "2"))
POOL_MAX = int(os.environ.get("DB_POOL_MAX", "10"))


def _get_pool():
    """Lazily built connection pool, or None if psycopg_pool isn't installed.

    Without this every request paid a fresh TCP + TLS + SCRAM handshake to the
    database. Against a remote host that is several hundred milliseconds, and
    opening a single project screen fires about six independent endpoints — so
    the handshakes alone dominated page load.
    """
    global _pool, _pool_unavailable
    if _pool is not None or _pool_unavailable:
        return _pool
    with _pool_lock:
        if _pool is not None or _pool_unavailable:
            return _pool
        try:
            from psycopg_pool import ConnectionPool
        except ImportError:
            _pool_unavailable = True
            print(
                "psycopg_pool is not installed — falling back to one connection "
                "per request, which is slow. Fix with: pip install 'psycopg_pool>=3.2'"
            )
            return None
        _pool = ConnectionPool(
            _PG_URL,
            min_size=POOL_MIN,
            max_size=POOL_MAX,
            kwargs={"autocommit": True, "row_factory": _pg_row_factory},
            timeout=15,
            max_idle=300,
            open=True,
        )
        return _pool


def get_connection():
    """A dedicated, unpooled connection. Used by init_db and the CLI scripts."""
    conn = psycopg.connect(
        _PG_URL,
        autocommit=True,
        row_factory=_pg_row_factory,
        connect_timeout=10,
    )
    return _PgConnection(conn)


def get_db():
    pool = _get_pool()
    if pool is None:
        conn = get_connection()
        try:
            yield conn
        finally:
            conn.close()
        return
    with pool.connection() as raw:
        yield _PgConnection(raw, owned=False)


def close_pool() -> None:
    """Release pooled connections on shutdown."""
    global _pool
    with _pool_lock:
        if _pool is not None:
            _pool.close()
            _pool = None


def init_db() -> None:
    """Apply the schema and seed data. Skippable with SKIP_DB_INIT=1.

    The DDL used to be sent one statement at a time — around sixty separate
    round trips to the database before the process could serve its first
    request. Postgres accepts the whole script in a single call, so this is now
    one round trip. Set SKIP_DB_INIT=1 on workers that don't need to migrate
    (only one process in a deployment has to run this).
    """
    if os.environ.get("SKIP_DB_INIT", "").strip().lower() in {"1", "true", "yes", "on"}:
        print("SKIP_DB_INIT is set — skipping schema/seed.")
        return
    conn = get_connection()
    try:
        raw = conn._conn
        script = re.sub(r"--[^\n]*", "", _PG_SCHEMA).strip()
        try:
            # psycopg sends a multi-statement script in one round trip.
            raw.execute(script)
        except psycopg.Error:
            # Fall back to statement-at-a-time so one unsupported statement
            # can't take the whole schema down.
            for statement in script.split(";"):
                statement = statement.strip()
                if statement:
                    raw.execute(statement)

        for statement in _OPTIONAL_DDL:
            try:
                raw.execute(statement)
            except psycopg.Error as exc:
                print(f"Optional DDL skipped ({exc.__class__.__name__}): {statement[:60]}…")
                if "idx_keywords_project_term" in statement:
                    # Plain ASCII on purpose. A Windows console defaults to
                    # cp1252, which has no U+2192, so an arrow here raised
                    # UnicodeEncodeError *inside the handler* and killed the
                    # whole server over what is only a warning.
                    print(
                        "  -> this project has duplicate keyword terms. Merge them with:\n"
                        "      cd server-python && python -m scripts.dedupe_keywords\n"
                        "    (add --commit once the dry run looks right)"
                    )

        _seed(conn)
    finally:
        conn.close()


def _seed_locations(conn) -> None:
    (have,) = conn.execute("SELECT COUNT(*) FROM locations").fetchone()
    if have == 0:
        from .locations import seed_rows

        rows = seed_rows()
        conn.executemany(
            "INSERT INTO locations (location_code, name, full_name, kind,"
            " country_code, region_code, country_iso, location_type, alt,"
            " name_key, search_key)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            rows,
        )
        print(f"Seeded {len(rows)} locations (countries + verified metro cities)")

    _backfill_location_keys(conn)


def _backfill_location_keys(conn) -> None:
    # EXISTS short-circuits on the first hit; COUNT(*) scanned the whole
    # locations table (~100k rows, and name_key isn't indexed) on every boot.
    row = conn.execute(
        "SELECT 1 FROM locations WHERE name_key IS NULL LIMIT 1"
    ).fetchone()
    if not row:
        return
    (stale,) = conn.execute("SELECT COUNT(*) FROM locations WHERE name_key IS NULL").fetchone()
    conn.execute(
        "UPDATE locations SET"
        "  name_key = LOWER(name),"
        "  search_key = ' ' || LOWER(REPLACE(REPLACE(REPLACE(full_name, ',', ' '), '  ', ' '), '  ', ' '))"
        "               || ' ' || LOWER(alt) || ' '"
        " WHERE name_key IS NULL"
    )
    print(f"Back-filled search keys on {stale:,} locations")


def _backfill_project_locations(conn) -> None:
    # Guard first: this UPDATE carries three correlated subqueries against
    # locations and used to run unconditionally on every startup, even when
    # there was nothing to backfill.
    row = conn.execute(
        "SELECT 1 FROM projects WHERE location_code IS NOT NULL"
        " AND country_code IS NULL LIMIT 1"
    ).fetchone()
    if not row:
        return
    conn.execute(
        "UPDATE projects SET"
        "  country_code = (SELECT l.country_code FROM locations l"
        "                  WHERE l.location_code = projects.location_code),"
        "  city_code = (SELECT CASE WHEN l.kind = 'city' THEN l.location_code END"
        "               FROM locations l WHERE l.location_code = projects.location_code),"
        "  location_label = (SELECT l.full_name FROM locations l"
        "                    WHERE l.location_code = projects.location_code)"
        " WHERE location_code IS NOT NULL AND country_code IS NULL"
    )


def _seed(conn) -> None:
    _seed_locations(conn)

    (count,) = conn.execute("SELECT COUNT(*) FROM users").fetchone()
    if count == 0:
        env_pw = os.environ.get("SEED_ADMIN_PASSWORD", "").strip()
        if not env_pw:
            print(
                "No users found and SEED_ADMIN_PASSWORD is unset — skipping the "
                "Super Admin seed. Set SEED_ADMIN_PASSWORD and restart to create it."
            )
        else:
            pw_hash = bcrypt.hashpw(env_pw.encode(), bcrypt.gensalt()).decode()
            conn.execute(
                "INSERT INTO users (name, email, role, password_hash, must_change_password, status)"
                " VALUES (?, ?, ?, ?, 1, 'active')",
                ("Soham Dhokiya", "soham@infyappdevelopment.com", "Super Admin", pw_hash),
            )
            print(
                "Seeded first Super Admin (soham@infyappdevelopment.com) — must change "
                "password on first sign-in. Only the bcrypt hash is stored; the "
                "password is never printed."
            )

    (pcount,) = conn.execute("SELECT COUNT(*) FROM projects").fetchone()
    if pcount == 0:
        cur = conn.execute(
            "INSERT INTO projects (name, domain, location_code, active) VALUES (?, ?, ?, 1)",
            ("Sattva Connect", "sattvaconnect.com", 2356),
        )
        sattva = cur.lastrowid
        kws = [
            (sattva, "online yoga classes", 4, 9, "2026-06-10"),
            (sattva, "yoga teacher training online", 12, 8, "2026-06-10"),
            (sattva, "meditation app for beginners", 21, 21, "2026-06-10"),
            (sattva, "pranayama breathing course", 3, None, "2026-06-11"),
        ]
        for kw in kws:
            conn.execute(
                "INSERT INTO keywords (project_id, term, current_rank, previous_rank, last_checked)"
                " VALUES (?, ?, ?, ?, ?)",
                kw,
            )
        cur = conn.execute(
            "INSERT INTO projects (name, domain, location_code, active) VALUES (?, ?, ?, 1)",
            ("Urban Bloom Florists", "urbanbloomflorists.in", 2356),
        )
        conn.execute(
            "INSERT INTO keywords (project_id, term, current_rank, previous_rank, last_checked)"
            " VALUES (?, ?, ?, ?, ?)",
            (cur.lastrowid, "same day flower delivery mumbai", 7, 11, "2026-06-09"),
        )
        conn.execute(
            "INSERT INTO projects (name, domain, location_code, active) VALUES (?, ?, ?, 0)",
            ("Peak Performance Gym", "peakperformancegym.in", 2356),
        )
        print("Seeded demo projects + keywords")

    _backfill_project_locations(conn)