import os
import re
import secrets

NO_ID_TABLES = {"email_otp", "password_otp", "user_projects", "locations"}

import bcrypt

from . import config  # noqa: F401  (imported for the .env side effect)

_SEED_PW_CHARS = "ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789"


def _looks_like_postgres(url: str) -> bool:
    return url.startswith((
        "postgresql://", "postgresql+psycopg://", "postgresql+psycopg2://", "postgres://",
    ))


def _normalize_pg_url(url: str) -> str:
    for prefix in ("postgresql+psycopg://", "postgresql+psycopg2://", "postgres://"):
        if url.startswith(prefix):
            return "postgresql://" + url[len(prefix):]
    return url


DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL is not set. This app runs on Postgres (Supabase) only —"
        " put the connection URL in server-python/.env."
    )
if not _looks_like_postgres(DATABASE_URL):
    raise RuntimeError(
        f"DATABASE_URL does not look like Postgres: {DATABASE_URL[:24]}… —"
        " expected postgresql://, postgres:// or postgresql+psycopg://."
    )
_PG_URL = _normalize_pg_url(DATABASE_URL)

import psycopg

INTEGRITY_ERRORS = (psycopg.IntegrityError,)


_PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 TEXT NOT NULL,
  email                TEXT NOT NULL UNIQUE,
  role                 TEXT NOT NULL CHECK (role IN ('Super Admin','Admin','Team','Client')),
  password_hash        TEXT NOT NULL,
  must_change_password INTEGER NOT NULL DEFAULT 0,
  status               TEXT NOT NULL DEFAULT 'invited' CHECK (status IN ('invited','active')),
  totp_secret          TEXT,
  totp_enabled         INTEGER NOT NULL DEFAULT 0,
  created_at           TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS emails (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  to_email TEXT NOT NULL,
  subject  TEXT NOT NULL,
  body     TEXT NOT NULL,
  sent_at  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS locations (
  location_code INTEGER PRIMARY KEY,
  name          TEXT NOT NULL,
  full_name     TEXT NOT NULL,
  kind          TEXT NOT NULL CHECK (kind IN ('country','region','city')),
  country_code  INTEGER,
  region_code   INTEGER,
  country_iso   TEXT,
  location_type TEXT,
  alt           TEXT NOT NULL DEFAULT '',
  name_key      TEXT,
  search_key    TEXT
);
ALTER TABLE locations ADD COLUMN IF NOT EXISTS name_key   TEXT;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS search_key TEXT;

DROP INDEX IF EXISTS idx_locations_kind_name;
DROP INDEX IF EXISTS idx_locations_kind_country;
DROP INDEX IF EXISTS idx_locations_kind_region;

CREATE INDEX IF NOT EXISTS idx_locations_key
  ON locations (kind, name_key text_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_locations_country_key
  ON locations (kind, country_code, name_key text_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_locations_region_key
  ON locations (kind, region_code, name_key text_pattern_ops);

CREATE TABLE IF NOT EXISTS projects (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL,
  domain          TEXT,
  location_code   INTEGER,
  country_code    INTEGER,
  region_code     INTEGER,
  city_code       INTEGER,
  location_label  TEXT,
  ga_property_id  TEXT,
  gsc_site_url    TEXT,
  active          INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS country_code   INTEGER;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS region_code    INTEGER;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS city_code      INTEGER;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS location_label TEXT;

CREATE TABLE IF NOT EXISTS keywords (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id    INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  term          TEXT NOT NULL,
  current_rank  INTEGER CHECK (current_rank >= 1),
  previous_rank INTEGER CHECK (previous_rank >= 1),
  last_checked  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD'),
  created_at    TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS snapshots (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  period_key  TEXT NOT NULL,
  label       TEXT NOT NULL,
  captured_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD'),
  created_at  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  source      TEXT NOT NULL DEFAULT 'manual',
  locked      INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS snapshot_ranks (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id  INTEGER NOT NULL REFERENCES snapshots(id) ON DELETE CASCADE,
  keyword_id   INTEGER REFERENCES keywords(id) ON DELETE SET NULL,
  term         TEXT NOT NULL,
  rank         INTEGER,
  last_checked TEXT
);

CREATE TABLE IF NOT EXISTS moz_metrics (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id       INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  domain           TEXT NOT NULL,
  domain_authority INTEGER,
  linking_domains  INTEGER,
  inbound_links    INTEGER,
  ranking_keywords INTEGER,
  spam_score       REAL,
  raw_json         TEXT,
  fetched_at       TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_projects (
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(user_id, project_id)
);

CREATE TABLE IF NOT EXISTS report_version (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id        INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  period_key        TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','in_review','sent')),
  parent_version_id INTEGER REFERENCES report_version(id) ON DELETE SET NULL,
  data_json         TEXT NOT NULL,
  content_json      TEXT NOT NULL DEFAULT '{}',
  rank_snapshot_id  INTEGER REFERENCES snapshots(id) ON DELETE SET NULL,
  created_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at        TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  frozen_at         TEXT
);

CREATE INDEX IF NOT EXISTS idx_report_version_project_period
  ON report_version (project_id, period_key);

CREATE TABLE IF NOT EXISTS backlinks (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  url         TEXT NOT NULL,
  month       TEXT NOT NULL,
  created_at  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(project_id, month, url)
);

CREATE INDEX IF NOT EXISTS idx_backlinks_project_month
  ON backlinks (project_id, month);

CREATE INDEX IF NOT EXISTS idx_keywords_project_created
  ON keywords (project_id, created_at, id);

CREATE TABLE IF NOT EXISTS keyword_ranks (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword_id INTEGER NOT NULL REFERENCES keywords(id) ON DELETE CASCADE,
  month      TEXT NOT NULL,
  rank       INTEGER CHECK (rank IS NULL OR rank >= 1),
  updated_at TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE(keyword_id, month)
);

CREATE INDEX IF NOT EXISTS idx_keyword_ranks_month
  ON keyword_ranks (month, keyword_id);

CREATE TABLE IF NOT EXISTS posts (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  kind        TEXT NOT NULL CHECK (kind IN ('blog','linkedin')),
  url         TEXT NOT NULL,
  title       TEXT,
  month       TEXT,
  created_at  TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_posts_project_kind ON posts (project_id, kind);
ALTER TABLE posts ADD COLUMN IF NOT EXISTS month TEXT;

CREATE INDEX IF NOT EXISTS idx_snapshot_ranks_snapshot
  ON snapshot_ranks (snapshot_id);
CREATE INDEX IF NOT EXISTS idx_snapshots_project_period
  ON snapshots (project_id, period_key);
CREATE INDEX IF NOT EXISTS idx_moz_metrics_project_fetched
  ON moz_metrics (project_id, fetched_at);

ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_secret TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_enabled INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS twofa_backup_codes (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash  TEXT NOT NULL,
  used_at    TEXT
);
CREATE INDEX IF NOT EXISTS idx_twofa_backup_user ON twofa_backup_codes (user_id);

CREATE TABLE IF NOT EXISTS email_otp (
  user_id     INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  code_hash   TEXT NOT NULL,
  expires_at  TEXT NOT NULL,
  attempts    INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS password_otp (
  user_id     INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  code_hash   TEXT NOT NULL,
  expires_at  TEXT NOT NULL,
  attempts    INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS rank_check_log (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  created_at  TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_rank_check_log_user_project
  ON rank_check_log (user_id, project_id, created_at);
"""


def _translate(sql: str, returning: bool = True) -> str:
    s = sql
    s = s.replace("strftime('%Y-%m','now')", "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM')")
    s = s.replace("datetime('now')", "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')")
    s = s.replace("date('now')", "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD')")

    head = s.lstrip()[:24].upper()
    if head.startswith("INSERT OR IGNORE"):
        i = s.upper().index("INSERT OR IGNORE")
        s = s[:i] + "INSERT" + s[i + len("INSERT OR IGNORE"):]
        if "ON CONFLICT" not in s.upper():
            s = s.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    elif returning and head.startswith("INSERT") and "RETURNING" not in s.upper():
        m = re.search(r"insert\s+into\s+\"?([a-zA-Z_]\w*)\"?", s, re.IGNORECASE)
        table = m.group(1).lower() if m else ""
        if table not in NO_ID_TABLES:
            s = s.rstrip().rstrip(";") + " RETURNING id"

    s = s.replace("?", "%s")
    return s


class _Row:

    __slots__ = ("_names", "_vals", "_index")

    def __init__(self, names, values):
        self._names = names
        self._vals = values
        self._index = None

    def __getitem__(self, key):
        if isinstance(key, str):
            if self._index is None:
                self._index = {n: i for i, n in enumerate(self._names)}
            return self._vals[self._index[key]]
        return self._vals[key]

    def __iter__(self):
        return iter(self._vals)

    def __len__(self):
        return len(self._vals)

    def keys(self):
        return list(self._names)

    def get(self, key, default=None):
        try:
            return self[key]
        except (KeyError, IndexError):
            return default


def _pg_row_factory(cursor):
    cols = cursor.description
    names = [c.name for c in cols] if cols else []

    def make_row(values):
        return _Row(names, values)

    return make_row


class _PgCursor:

    __slots__ = ("_cur", "lastrowid")

    def __init__(self, cur, translated_sql):
        self._cur = cur
        self.lastrowid = None
        if translated_sql.lstrip()[:6].upper() == "INSERT" and "RETURNING" in translated_sql.upper():
            row = cur.fetchone()
            self.lastrowid = row[0] if row is not None else None

    @property
    def rowcount(self):
        return self._cur.rowcount

    def fetchone(self):
        return self._cur.fetchone()

    def fetchall(self):
        return self._cur.fetchall()

    def fetchmany(self, size=None):
        return self._cur.fetchmany() if size is None else self._cur.fetchmany(size)


class _PgConnection:

    __slots__ = ("_conn",)

    def __init__(self, conn):
        self._conn = conn

    def execute(self, sql, params=()):
        translated = _translate(sql)
        cur = self._conn.cursor()
        cur.execute(translated, params or None)
        return _PgCursor(cur, translated)

    def executemany(self, sql, seq_of_params):
        translated = _translate(sql, returning=False)
        rows = list(seq_of_params)
        cur = self._conn.cursor()
        if rows:
            cur.executemany(translated, rows)
        return _PgCursor(cur, translated)

    def close(self):
        self._conn.close()


def get_connection():
    conn = psycopg.connect(
        _PG_URL,
        autocommit=True,
        row_factory=_pg_row_factory,
        connect_timeout=10,
    )
    return _PgConnection(conn)


def get_db():
    conn = get_connection()
    try:
        yield conn
    finally:
        conn.close()


def init_db() -> None:
    conn = get_connection()
    try:
        raw = conn._conn
        for statement in re.sub(r"--[^\n]*", "", _PG_SCHEMA).split(";"):
            statement = statement.strip()
            if statement:
                raw.execute(statement)
        _seed(conn)
    finally:
        conn.close()


def _seed_locations(conn) -> None:
    (have,) = conn.execute("SELECT COUNT(*) FROM locations").fetchone()
    if have == 0:
        from .locations import seed_rows

        rows = seed_rows()
        conn.executemany(
            "INSERT INTO locations (location_code, name, full_name, kind,"
            " country_code, region_code, country_iso, location_type, alt,"
            " name_key, search_key)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            rows,
        )
        print(f"Seeded {len(rows)} locations (countries + verified metro cities)")

    _backfill_location_keys(conn)


def _backfill_location_keys(conn) -> None:
    (stale,) = conn.execute("SELECT COUNT(*) FROM locations WHERE name_key IS NULL").fetchone()
    if not stale:
        return
    conn.execute(
        "UPDATE locations SET"
        "  name_key = LOWER(name),"
        "  search_key = ' ' || LOWER(REPLACE(REPLACE(REPLACE(full_name, ',', ' '), '  ', ' '), '  ', ' '))"
        "               || ' ' || LOWER(alt) || ' '"
        " WHERE name_key IS NULL"
    )
    print(f"Back-filled search keys on {stale:,} locations")


def _backfill_project_locations(conn) -> None:
    conn.execute(
        "UPDATE projects SET"
        "  country_code = (SELECT l.country_code FROM locations l"
        "                  WHERE l.location_code = projects.location_code),"
        "  city_code = (SELECT CASE WHEN l.kind = 'city' THEN l.location_code END"
        "               FROM locations l WHERE l.location_code = projects.location_code),"
        "  location_label = (SELECT l.full_name FROM locations l"
        "                    WHERE l.location_code = projects.location_code)"
        " WHERE location_code IS NOT NULL AND country_code IS NULL"
    )


def _seed(conn) -> None:
    _seed_locations(conn)

    (count,) = conn.execute("SELECT COUNT(*) FROM users").fetchone()
    if count == 0:
        env_pw = os.environ.get("SEED_ADMIN_PASSWORD", "").strip()
        if not env_pw:
            print(
                "No users found and SEED_ADMIN_PASSWORD is unset — skipping the "
                "Super Admin seed. Set SEED_ADMIN_PASSWORD and restart to create it."
            )
        else:
            pw_hash = bcrypt.hashpw(env_pw.encode(), bcrypt.gensalt()).decode()
            conn.execute(
                "INSERT INTO users (name, email, role, password_hash, must_change_password, status)"
                " VALUES (?, ?, ?, ?, 1, 'active')",
                ("Soham Dhokiya", "soham@infyappdevelopment.com", "Super Admin", pw_hash),
            )
            print(
                "Seeded first Super Admin (soham@infyappdevelopment.com) — must change "
                "password on first sign-in. Only the bcrypt hash is stored; the "
                "password is never printed."
            )

    (pcount,) = conn.execute("SELECT COUNT(*) FROM projects").fetchone()
    if pcount == 0:
        cur = conn.execute(
            "INSERT INTO projects (name, domain, location_code, active) VALUES (?, ?, ?, 1)",
            ("Sattva Connect", "sattvaconnect.com", 2356),
        )
        sattva = cur.lastrowid
        kws = [
            (sattva, "online yoga classes", 4, 9, "2026-06-10"),
            (sattva, "yoga teacher training online", 12, 8, "2026-06-10"),
            (sattva, "meditation app for beginners", 21, 21, "2026-06-10"),
            (sattva, "pranayama breathing course", 3, None, "2026-06-11"),
        ]
        for kw in kws:
            conn.execute(
                "INSERT INTO keywords (project_id, term, current_rank, previous_rank, last_checked)"
                " VALUES (?, ?, ?, ?, ?)",
                kw,
            )
        cur = conn.execute(
            "INSERT INTO projects (name, domain, location_code, active) VALUES (?, ?, ?, 1)",
            ("Urban Bloom Florists", "urbanbloomflorists.in", 2356),
        )
        conn.execute(
            "INSERT INTO keywords (project_id, term, current_rank, previous_rank, last_checked)"
            " VALUES (?, ?, ?, ?, ?)",
            (cur.lastrowid, "same day flower delivery mumbai", 7, 11, "2026-06-09"),
        )
        conn.execute(
            "INSERT INTO projects (name, domain, location_code, active) VALUES (?, ?, ?, 0)",
            ("Peak Performance Gym", "peakperformancegym.in", 2356),
        )
        print("Seeded demo projects + keywords")

    _backfill_project_locations(conn)
